apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:sts::378582414855:assumed-role/codebuild-viper-frontend-app-service-role/codebuild-session-role
      groups:
         - system:bootstrappers
         - system:nodes
         - system:master             