version: 0.2

env:
  variables:
    cluster: "viper"
    appName: "viper_forntend_app_test"
 

phases:
  install:
    commands:
  #    - npm install -g node
  pre_build:
    commands:
      - ls -las
      - export VERSION=$(sed 's/.*"version" "\(.*\)".*/\1/;t;d' package.json)
      - echo ${VERSION}
      - npm install
  build:
    commands:
      - npm build
  post_build:
    commands:
      - echo Entered the post_build phase...

      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS  --password-stdin 378582414855.dkr.ecr.eu-central-1.amazonaws.com

      - aws ecr describe-repositories --repository-names ${cluster}/${appName} || aws ecr create-repository --repository-name ${cluster}/${appName}

      - docker build -t ${appName} .

      - docker tag ${appName}:latest 378582414855.dkr.ecr.eu-central-1.amazonaws.com/${cluster}/${appName}:latest

      - docker tag ${appName} 378582414855.dkr.ecr.eu-central-1.amazonaws.com/${cluster}/${appName}:${VERSION}

      - docker push 378582414855.dkr.ecr.eu-central-1.amazonaws.com/${cluster}/${appName}

      - echo Build completed on `date`

      - 

    
     

artifacts:
  files:
    - '**/*'
  base-directory: dist