version: 0.2

phases:
  install:
    commands:
  #    - npm install -g node
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm build
  post_build:
    commands:
      - echo Entered the post_build phase...

      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS  --password-stdin 378582414855.dkr.ecr.eu-central-1.amazonaws.com

      - docker build -t viper_forntend_app_test .

      - docker tag viper_forntend_app_test:latest 378582414855.dkr.ecr.eu-central-1.amazonaws.com/viper_forntend_app_test:latest

      - docker tag viper_forntend_app_test:1.2.3 378582414855.dkr.ecr.eu-central-1.amazonaws.com/viper_forntend_app_test:1.2.3

      - docker push 378582414855.dkr.ecr.eu-central-1.amazonaws.com/aws_ecr_test:latest

      - echo Build completed on `date`
    
     

artifacts:
  files:
    - '**/*'
  base-directory: dist