apiVersion: v1
clusters:
- cluster:
    server: https://9C046E61AD382C2FB49E05A3CE742DEB.gr7.eu-central-1.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EUXhOVEUwTURJek0xb1hEVE13TURReE16RTBNREl6TTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSjNZCjAzM25qT1RoL0loWk1zYXp5bGE3N2h0ZFlkQzRBMzB6aWcyZnhuc2ZGQ0Z5TlhmUkpFYXB4Um9QbDdnVjZlQVkKUWtJUStPUXN4YWtJNm54Y3pqZXI5d3Z0ZlV2Z2FhYm5LZWgyMDVHQS9ERXhxeGh6cEQ5TWp3ZkJlM3hJNld2aQpBY1VFVElNa0ZnQ1kxbVRzSUx2Y2RJUnpDNVBwajNPazhqUnlXRERKaStCTFFMMGJ3SVhDcDlyTDNYdGQ2eTR0Ci9zUDYyQ1YyTnViZU1RV2VvTGpaWFlqT1E1bHNRMTRwVFF6VDFDMk4xSngzOVlZdGM0UzJIL1ZONlhtUERWdEYKTUtGZE1EVlVMS0ZCdUJrbDhOajl1YW90R2JsYWhDWjVVWU4vYUhNNU9BeXp1cU85MVBVQXQxbzNoT2ZrYnp2eAo4dVZwNDMrWG1CQXR4RDcrNFpNQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFGTjZqUHN6dHhIMEZLYWhQbUl0UXRUR2EvN2EKMWV1NllRVW5WOXFZb2w5N3ozdXg1dUR0SUpnL2Z5eXp0ejJTT3FsUHNwMVlOM0txbkU3VnJrWnJGR0ZxR2hvVwp6b3ZOcENkU1o2VGNtVjhZRUJzcERDRUNPendEbzRoWUxLUG5LUlQrRVRIZGhMVTV1TmZmaVpoR2k4Y1ZEZHdJCjR2d2I4ZWsraS82cDFmR2RzSE1tWUVJY1hMb0p1MEhQSks4T21uckNFRnM3MlVDeWhuZ1FnODBVNFNVUjFtUzkKY2hsamVxNENvMFFTRnQ3SStxTk5kVWI2a0RSQkhFcFAzeDJ5U2NQUjh0OEdsM2pFeFQ0b05TTjEzTGFadGJGWApHb29pVStUUmhKK0ZkL1lRS3FnczA0V2VlVG5DdzNEaEU5SXhsVEJ2M0tWcHA2TFRadzFyNTdDUnl4OD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: my-user
  name: my-context
current-context: my-context
kind: Config
preferences: {}
users:
- name: my-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "eks-cluster"
        - "-r"
        - "Iteratec-Test-MK"
